export const quotesList = [
  "It's a dangerous business, Frodo, going out your door. You step onto the road, and if you don't keep your feet, there's no knowing where you might be swept off to.",
  "Moonlight drowns out all but the brightest stars.",
  "Home is behind, the world ahead and there are many paths to tread through shadows to the edge of night until the stars are all alight.",
  "Some who have read the book, or at any rate have reviewed it, have found it boring, absurd, or contemptible, and I have no cause to complain, since I have similar opinions of their works, or of the kinds of writing that they evidently prefer.",
  "I would rather spend one lifetime with you, than face all the ages of this world alone.",
  "I will hate the man you choose because he isn't me, and love him if he makes you smile.",
  "Clocks slay time... time is dead as long as it is being clicked off by little wheels; only when the clock stops does time come to life.",
  "It does not do to dwell on dreams and forget to live.",
  "I solemnly swear that I am up to no good.",
  "It takes a great deal of bravery to stand up to our enemies, but just as much to stand up to our friends.",
  "Do not pity the dead, Harry. Pity the living, and, above all those who live without love.",
  "Remember, if the time should come when you have to make a choice between what is right and what is easy, remember what happened to a boy who was good, and kind, and brave, because he strayed across the path of Lord Voldemort. Remember Cedric Diggory",
  "Numbing the pain for a while will make it worse when you finally feel it.",
  "Just because you have the emotional range of a teaspoon doesn't mean we all have.",
  "We're all human, aren't we? Every human life is worth the same, and worth saving.",
  "I no longer believed in the idea of soul mates, or love at first sight. But I was beginning to believe that a very few times in your life, if you were lucky, you might meet someone who was exactly right for you. Not because he was perfect, or because you were, but because your combined flaws were arranged in a way that allowed two separate beings to hinge together.",
  "They didn’t agree on much. In fact, they didn’t agree on anything. They fought all the time and challenged each other ever day. But despite their differences, they had one important thing in common. They were crazy about each other.",
  "I cannot fix on the hour, or the spot, or the look or the words, which laid the foundation. It is too long ago. I was in the middle before I knew that I had begun.",
  "When love is not madness it is not love.",
  "Never close your lips to those whom you have already opened your heart.",
  "Let's fall, or rather rise, in Love.",
  "I ask you to pass through life at my side—to be my second self, and best earthly companion.",
  "I love that you get cold when it's 71 degrees out. I love that it takes you an hour and a half to order a sandwich. I love that you get a little crinkle above your nose when you're looking at me like I'm nuts. I love that after I spend the day with you, I can still smell your perfume on my clothes. And I love that you are the last person I want to talk to before I go to sleep at night. And it's not because I'm lonely, and it's not because it's New Year's Eve. I came here tonight because when you realize you want to spend the rest of your life with somebody, you want the rest of your life to start as soon as possible.",
  "I'll hold you 'til the end of time, if that's all you want from me. But there's so much more I could do for you. I would treasure you. Marry me, Cassandra- and we'll tell them all to go to hell.",
  "What right had I to imagine that she would wish to unite her life with mine? Who and What am I? A man of no account, wanted by no one and of no use to anyone.",
  "But better to get hurt by the truth than comforted with a lie.",
  "For you, a thousand times over",
  "I suspect the truth is that we are waiting, all of us, against insurmountable odds, for something extraordinary to happen to us.",
  "One could not count the moons that shimmer on her roofs Or the thousand splendid suns that hide behind her walls.",
  "Of all the hardships a person had to face, none was more punishing than the simple act of waiting",
  "Like a compass needle that points north, a man's accusing finger always finds a woman. Always.",
];
